<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ur3e_hande_moveit_py</name>
  <version>0.0.0</version>
  <description>Arm-only Python node to move the UR3e to a detected object pose using PyMoveIt2.</description>
  <maintainer email="enwerem@terpmail.umd.edu">Clinton Enwerem</maintainer>
  <license>Apache-2.0</license>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>ur3e_hande_planning_interfaces</depend>
  <depend>pymoveit2</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
